
package com.company.sushchanka.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServiceImpl", targetNamespace = "http://service.sushchanka.company.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateUserTask", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.UpdateUserTask")
    @ResponseWrapper(localName = "updateUserTaskResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.UpdateUserTaskResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/updateUserTaskRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/updateUserTaskResponse")
    public void updateUserTask(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Task arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.company.sushchanka.service.Task
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserTaskByIdTask", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.FindUserTaskByIdTask")
    @ResponseWrapper(localName = "findUserTaskByIdTaskResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.FindUserTaskByIdTaskResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/findUserTaskByIdTaskRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/findUserTaskByIdTaskResponse")
    public Task findUserTaskByIdTask(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteTaskOfUserById", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.DeleteTaskOfUserById")
    @ResponseWrapper(localName = "deleteTaskOfUserByIdResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.DeleteTaskOfUserByIdResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/deleteTaskOfUserByIdRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/deleteTaskOfUserByIdResponse")
    public void deleteTaskOfUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAllUserTasks", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.DeleteAllUserTasks")
    @ResponseWrapper(localName = "deleteAllUserTasksResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.DeleteAllUserTasksResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/deleteAllUserTasksRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/deleteAllUserTasksResponse")
    public void deleteAllUserTasks(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.company.sushchanka.service.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllUsers", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.FindAllUsers")
    @ResponseWrapper(localName = "findAllUsersResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.FindAllUsersResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/findAllUsersRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/findAllUsersResponse")
    public List<User> findAllUsers();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.company.sushchanka.service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.FindByIdResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/findByIdRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/findByIdResponse")
    public User findById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.company.sushchanka.service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByName", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.FindByName")
    @ResponseWrapper(localName = "findByNameResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.FindByNameResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/findByNameRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/findByNameResponse")
    public User findByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveUser", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.SaveUser")
    @ResponseWrapper(localName = "saveUserResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.SaveUserResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/saveUserRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/saveUserResponse")
    public void saveUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.UpdateUserResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/updateUserRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/updateUserResponse")
    public void updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUserById", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.DeleteUserById")
    @ResponseWrapper(localName = "deleteUserByIdResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.DeleteUserByIdResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/deleteUserByIdRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/deleteUserByIdResponse")
    public void deleteUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAllUsers", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.DeleteAllUsers")
    @ResponseWrapper(localName = "deleteAllUsersResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.DeleteAllUsersResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/deleteAllUsersRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/deleteAllUsersResponse")
    public void deleteAllUsers();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isUserExist", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.IsUserExist")
    @ResponseWrapper(localName = "isUserExistResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.IsUserExistResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/isUserExistRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/isUserExistResponse")
    public boolean isUserExist(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.company.sushchanka.service.Task>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllUserTasks", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.FindAllUserTasks")
    @ResponseWrapper(localName = "findAllUserTasksResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.FindAllUserTasksResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/findAllUserTasksRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/findAllUserTasksResponse")
    public List<Task> findAllUserTasks(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isTaskExist", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.IsTaskExist")
    @ResponseWrapper(localName = "isTaskExistResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.IsTaskExistResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/isTaskExistRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/isTaskExistResponse")
    public boolean isTaskExist(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Task arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.company.sushchanka.service.Task
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findTaskByName", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.FindTaskByName")
    @ResponseWrapper(localName = "findTaskByNameResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.FindTaskByNameResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/findTaskByNameRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/findTaskByNameResponse")
    public Task findTaskByName(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveTask", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.SaveTask")
    @ResponseWrapper(localName = "saveTaskResponse", targetNamespace = "http://service.sushchanka.company.com/", className = "com.company.sushchanka.service.SaveTaskResponse")
    @Action(input = "http://service.sushchanka.company.com/UserServiceImpl/saveTaskRequest", output = "http://service.sushchanka.company.com/UserServiceImpl/saveTaskResponse")
    public void saveTask(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Task arg1);

}
